# Generated by Django 6.0.5 on 2026-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
