# Generated by Django 6.0.5 on 2026-06-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='provider_transactionn_id',
            new_name='provider_transaction_id',
        ),
    ]
