# Generated by Django 6.0.5 on 2026-05-30 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_funding', 'Pending Funding'), ('funded', 'Funded'), ('release_pending', 'Release Pending'), ('released', 'Released'), ('partially_released', 'Partially Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending_funding', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.userproject')),
            ],
        ),
    ]
